### ISSUE TITLE
The download link is broken...

### ISSUE THREAD

**Issue by Coolxiaolin** [ZENGXH/DMM_Net#2]
The extracted proposals can't be downloaded.
Besides, youtubeVOS-2018 dataset doesn't contains 'train_testdev_ot'

**Comment by ZENGXH** [comment]
Fixed the link. The `train_testdev_ot` is created from the first frame with annotation. I also add the link in README.md. :)

**Comment by Coolxiaolin** [comment]
Now it works fine. Thx
