### ISSUE TITLE
Do you have any helper scripts to process a mp4 / mov file?

### ISSUE THREAD

**Issue by 8secz-johndpope** [ZENGXH/DMM_Net#9]
I have another ticket open here
https://github.com/z-x-yang/CFBI/issues/10

They've created something similar to this repo.

It seems doable - need spit out individual pngs from video 
```shell
ffmpeg -i VIDEOHERE.mov %04d_img.png -hide_banner

```
but the way the code is tangled with meta.json makes things a tad difficult. Is there a shortcut or any scripts you can provide?

**Comment by ZENGXH** [comment]
you may want to check the scripts here: https://github.com/ZENGXH/DMM_Net/blob/ad34cc76ef9c7509e598ee47ade7d7da312d2191/tools/make_train_online_dataset.py#L29 which is used to create the `meta.json`. Hope it help!

**Comment by 8secz-johndpope** [comment]
thank you!
